{% set name = "r-cmdstanr" %}
{% set version = "0.9.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/cmdstanr/archive/v{{ version }}.tar.gz
  sha256: 55e1d9f7d2dba08771850243944606020c9ca4e682ff53ab6a4e9fbc3032a003

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}git
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-checkmate
    - r-data.table
    - r-jsonlite >=1.2.0
    - r-posterior >=1.4.1
    - r-processx >=3.5.0
    - r-r6 >=2.4.0
    - r-rlang >=0.4.7
    - r-withr >=2.5.0
  run:
    - r-base
    - r-checkmate
    - r-data.table
    - r-jsonlite >=1.2.0
    - r-posterior >=1.4.1
    - r-processx >=3.5.0
    - r-r6 >=2.4.0
    - r-rlang >=0.4.7
    - r-withr >=2.5.0
    - cmdstan

test:
  commands:
    - $R -e "library('cmdstanr')"                   # [not win]
    - $R -e "cmdstanr::cmdstan_version()"           # [not win]
    - "\"%R%\" -e \"library('cmdstanr')\""          # [win]
    - "\"%R%\" -e \"cmdstanr::cmdstan_version()\""  # [win]

about:
  home: https://github.com/stan-dev/cmdstanr
  license: BSD-3-Clause
  summary: CmdStanR is a lightweight interface to Stan for R users
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - mediocretech
